general:
  model_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_256/deeplab_v3_mobilenetv2_05_16_256_asppv2_qdq_int8.onnx
  config_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_256/deeplab_v3_mobilenetv2_05_16_256_asppv2_config.yaml
  dataset_path: ../../stm32ai-modelzoo-services/semantic_segmentation/datasets/semseg_validation_dataset/images
  test_masks_path: ../../stm32ai-modelzoo-services/semantic_segmentation/datasets/semseg_validation_dataset/masks
  test_files_path: ../../stm32ai-modelzoo-services/semantic_segmentation/datasets/semseg_validation_dataset/test_nano_full.txt

parameters:
  profile: profile_O3
  input_type: uint8     # int8 / uint8 / float32
  output_type: int8     # int8 / uint8 / float32
  input_chpos: chlast   # chlast / chfirst
  output_chpos: chlast  # chlast / chfirst
  evaluation_target: stedgeai_n6 # host, stedgeai_host, stedgeai_n6

tools:
   stedgeai:
      path_to_stedgeai: C:/ST/STEdgeAI_Core/2.0/Utilities/windows/stedgeai.exe
      path_to_loader: C:/ST/STEdgeAI_Core/2.0/scripts/N6_scripts/n6_loader.py

hydra:
  verbose: false
  job_logging:
    level: ERROR
  output_subdir: null
  run:
    dir: ./experiments_outputs
    
