general:
   model_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_512/deeplab_v3_mobilenetv2_05_16_512_asppv1.h5

operation_mode: evaluation

dataset:
   name: pascal_voc
   class_names: ["background", "aeroplane", "bicycle", "bird", "boat", "bottle", "bus",    #Or, classes_file_path
                "car", "cat", "chair", "cow", "dining table", "dog", "horse", "motorbike",
                "person", "potted plant", "sheep", "sofa", "train", "tv/monitor"]
   test_path: ./datasets/VOC2012_train_val/JPEGImages
   test_masks_path: ./datasets/VOC2012_train_val/SegmentationClassAug
   test_files_path: ./datasets/VOC2012_train_val/ImageSets/Segmentation/val.txt

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}