general:
  model_path: ../../stm32ai-modelzoo/semantic_segmentation/deeplab_v3/ST_pretrainedmodel_public_dataset/person_coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_320/deeplab_v3_mobilenetv2_05_16_320_asppv2.h5

operation_mode: quantization

dataset:
  name: person_pascal_voc
  quantization_path: ./datasets/VOC2012/JPEGImages
  quantization_masks_path: ./datasets/VOC2012/SegmentationClass
  quantization_files_path: ./datasets/VOC2012/ImageSets/Segmentation/onnx_quant.txt

preprocessing:
  rescaling: { scale: 1/255, offset: 0 }
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_channel
  quantization_type: PTQ
  quantization_input_type: float 
  quantization_output_type: float
  extra_options: calib_moving_average
  export_dir: quantized_models


mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}